//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcProgrammimgTutorialWebForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcProgrammimgTutorialWebForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a company first to delete.
        /// </summary>
        internal static string CompaniesWebForm_DeleteCompanyClick_Please_select_a_company_first_to_delete {
            get {
                return ResourceManager.GetString("CompaniesWebForm_DeleteCompanyClick_Please_select_a_company_first_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no companies to delete.
        /// </summary>
        internal static string CompaniesWebForm_DeleteCompanyClick_There_are_no_companies_to_delete {
            get {
                return ResourceManager.GetString("CompaniesWebForm_DeleteCompanyClick_There_are_no_companies_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete this Company.
        /// </summary>
        internal static string CompaniesWebForm_DeleteCompanyClick_You_cant_delete_this_Company {
            get {
                return ResourceManager.GetString("CompaniesWebForm_DeleteCompanyClick_You_cant_delete_this_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check a document first to delete.
        /// </summary>
        internal static string DocumentsWebForm_DeleteDocumentClick_Please_check_a_document_first_to_delete {
            get {
                return ResourceManager.GetString("DocumentsWebForm_DeleteDocumentClick_Please_check_a_document_first_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant delete documents you dont own!!!.
        /// </summary>
        internal static string DocumentsWebForm_DeleteDocumentClick_You_cant_delete_documents_you_dont_own___ {
            get {
                return ResourceManager.GetString("DocumentsWebForm_DeleteDocumentClick_You_cant_delete_documents_you_dont_own___", resourceCulture);
            }
        }
    }
}
