//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcProgrammingTutorial.UI.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DcProgrammingTutorial.UI.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the companies from database.
        /// </summary>
        internal static string DocumentDetailForm_DocumentDetailForm_Could_not_read_the_companies_from_database {
            get {
                return ResourceManager.GetString("DocumentDetailForm_DocumentDetailForm_Could_not_read_the_companies_from_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the document.
        /// </summary>
        internal static string DocumentDetailForm_SaveButtonClick_Could_not_create_the_document {
            get {
                return ResourceManager.GetString("DocumentDetailForm_SaveButtonClick_Could_not_create_the_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update the document.
        /// </summary>
        internal static string DocumentDetailForm_SaveButtonClick_Could_not_update_the_document {
            get {
                return ResourceManager.GetString("DocumentDetailForm_SaveButtonClick_Could_not_update_the_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must have a valid name.
        /// </summary>
        internal static string DocumentDetailForm_SaveButtonClick_Document_must_have_a_valid_name {
            get {
                return ResourceManager.GetString("DocumentDetailForm_SaveButtonClick_Document_must_have_a_valid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a valid name to your document.
        /// </summary>
        internal static string DocumentDetailForm_SaveButtonClick_Give_a_valid_name_to_your_document {
            get {
                return ResourceManager.GetString("DocumentDetailForm_SaveButtonClick_Give_a_valid_name_to_your_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not refresh the list.
        /// </summary>
        internal static string MainListForm_DeleteDocumentButtonClick_Could_not_refresh_the_list {
            get {
                return ResourceManager.GetString("MainListForm_DeleteDocumentButtonClick_Could_not_refresh_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document couldn&apos;t reomoved.
        /// </summary>
        internal static string MainListForm_DeleteDocumentButtonClick_Document_couldn_t_reomoved {
            get {
                return ResourceManager.GetString("MainListForm_DeleteDocumentButtonClick_Document_couldn_t_reomoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our list is empty.
        /// </summary>
        internal static string MainListForm_DeleteDocumentButtonClick_Our_list_is_empty {
            get {
                return ResourceManager.GetString("MainListForm_DeleteDocumentButtonClick_Our_list_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected document couldn&apos;t be deleted.
        /// </summary>
        internal static string MainListForm_DeleteDocumentButtonClick_The_selected_document_couldn_t_be_deleted {
            get {
                return ResourceManager.GetString("MainListForm_DeleteDocumentButtonClick_The_selected_document_couldn_t_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any document on our list.
        /// </summary>
        internal static string MainListForm_DeleteDocumentButtonClick_There_isn_t_any_document_on_our_list {
            get {
                return ResourceManager.GetString("MainListForm_DeleteDocumentButtonClick_There_isn_t_any_document_on_our_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not calculate the balance.
        /// </summary>
        internal static string MainListForm_DocumentAddedToListEvent_Could_not_calculate_the_balance {
            get {
                return ResourceManager.GetString("MainListForm_DocumentAddedToListEvent_Could_not_calculate_the_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our list is empty!.
        /// </summary>
        internal static string MainListForm_DocumentControllerOnDocumentAddedToList_Our_list_is_empty_ {
            get {
                return ResourceManager.GetString("MainListForm_DocumentControllerOnDocumentAddedToList_Our_list_is_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string MainListForm_EnterButtonClick_Name_cannot_be_empty {
            get {
                return ResourceManager.GetString("MainListForm_EnterButtonClick_Name_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the event.
        /// </summary>
        internal static string MainListForm_EXitToolStripMenuItemClick_Could_not_remove_the_event {
            get {
                return ResourceManager.GetString("MainListForm_EXitToolStripMenuItemClick_Could_not_remove_the_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read from database.
        /// </summary>
        internal static string MainListForm_MainListFormLoad_Could_not_read_from_database {
            get {
                return ResourceManager.GetString("MainListForm_MainListFormLoad_Could_not_read_from_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not refresh the list.
        /// </summary>
        internal static string MainListForm_RefreshGrid_Could_not_refresh_the_list {
            get {
                return ResourceManager.GetString("MainListForm_RefreshGrid_Could_not_refresh_the_list", resourceCulture);
            }
        }
    }
}
