// --------------------------------------------------------------------------------------------------------------------
// <copyright file="201611221005238_IgnoredAutoGenertatedIdColumn.cs" company="">
//   
// </copyright>
// <summary>
//   The ignored auto genertated id column.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace DcProgrammingTutorial.Lib.Migrations
{
    #region

    using System.Data.Entity.Migrations;

    #endregion

    /// <summary>
    /// The ignored auto genertated id column.
    /// </summary>
    public partial class IgnoredAutoGenertatedIdColumn : DbMigration
    {
        /// <summary>
        /// The down.
        /// </summary>
        public override void Down()
        {
            this.AddColumn("dbo.Document", "AutoGeneratedId", c => c.Boolean(nullable: false));
            this.AddColumn("dbo.Company", "AutoGeneratedId", c => c.Boolean(nullable: false));
        }

        /// <summary>
        /// The up.
        /// </summary>
        public override void Up()
        {
            this.DropColumn("dbo.Company", "AutoGeneratedId");
            this.DropColumn("dbo.Document", "AutoGeneratedId");
        }
    }
}