// --------------------------------------------------------------------------------------------------------------------
// <copyright file="201611220923256_Initial.cs" company="DataCommunication">
//   DcProgrammingTutorial
// </copyright>
// <summary>
//   The initial.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace DcProgrammingTutorial.Lib.Migrations
{
    #region

    using System.Data.Entity.Migrations;

    #endregion

    /// <summary>
    /// The initial.
    /// </summary>
    public partial class Initial : DbMigration
    {
        /// <summary>
        /// The down.
        /// </summary>
        public override void Down()
        {
            this.DropForeignKey("dbo.Document", "CompanyId", "dbo.Company");
            this.DropIndex("dbo.Document", new[] { "CompanyId" });
            this.DropTable("dbo.Document");
            this.DropTable("dbo.Company");
        }

        /// <summary>
        /// The up.
        /// </summary>
        public override void Up()
        {
            this.CreateTable(
                "dbo.Company",
                c =>
                    new
                        {
                            Id = c.Int(nullable: false, identity: true),
                            Active = c.Boolean(nullable: false),
                            Code = c.String(),
                            Name = c.String(nullable: false),
                            Created = c.DateTime(nullable: false),
                            Updated = c.DateTime(),
                            Deleted = c.DateTime(),
                            CreatedBy = c.String(),
                            UpdatedBy = c.String(),
                            DeletedBy = c.String(),
                            AutoGeneratedId = c.Boolean(nullable: false),
                        }).PrimaryKey(t => t.Id);

            this.CreateTable(
                "dbo.Document",
                c =>
                    new
                        {
                            Id = c.Int(nullable: false, identity: true),
                            Balance = c.Double(nullable: false),
                            Code = c.String(),
                            CompanyId = c.Int(),
                            Name = c.String(nullable: false),
                            Created = c.DateTime(nullable: false),
                            Updated = c.DateTime(),
                            Deleted = c.DateTime(),
                            CreatedBy = c.String(),
                            UpdatedBy = c.String(),
                            DeletedBy = c.String(),
                            AutoGeneratedId = c.Boolean(nullable: false),
                        }).PrimaryKey(t => t.Id).ForeignKey("dbo.Company", t => t.CompanyId).Index(t => t.CompanyId);
        }
    }
}