// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CompanyConfiguration.cs" company="Data Communication">
//   Dc Tutorial
// </copyright>
// <summary>
//   The company configuration.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace DcProgrammingTutorial.Lib.DBContext.Configurations
{
    #region

    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.ModelConfiguration;

    using DcProgrammingTutorial.Lib.Model.Persistent;

    #endregion

    /// <summary>
    /// The company configuration.
    /// </summary>
    public class CompanyConfiguration : EntityTypeConfiguration<Company>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyConfiguration"/> class.
        /// </summary>
        public CompanyConfiguration()
        {
            this.ToTable("Company");

            // Primary Keys
            this.HasKey(x => x.Id);
            this.Property(x => x.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            // Foreign Keys
            this.HasMany(x => x.Documents).WithOptional(x => x.Company).HasForeignKey(x => x.CompanyId);

            // Required Entities
            this.Property(x => x.Name).IsRequired();
            this.Property(x => x.Code).IsRequired();
            this.Property(x => x.TaxId).IsRequired();
            this.Ignore(x => x.AutoGeneratedId);
        }
    }
}