// --------------------------------------------------------------------------------------------------------------------
// <copyright file="DocumentConfiguration.cs" company="Data Communication">
//   DC Tutorial
// </copyright>
// <summary>
//   The document configuration.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace DcProgrammingTutorial.Lib.DBContext.Configurations
{
    #region

    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.ModelConfiguration;

    using DcProgrammingTutorial.Lib.Model.Persistent;

    #endregion

    /// <summary>
    /// The document configuration.
    /// </summary>
    public class DocumentConfiguration : EntityTypeConfiguration<Document>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentConfiguration"/> class.
        /// </summary>
        public DocumentConfiguration()
        {
            this.ToTable("Document");

            // Primary Keys
            this.HasKey(x => x.Id);
            this.Property(x => x.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            // Required Entities
            this.Property(x => x.Name).IsRequired();

            this.Ignore(x => x.AutoGeneratedId);
        }
    }
}